baseURL = "https://haydenstites.github.io/"
languageCode = "en-us"
enablerobotstxt = true
enableemoji = true
copyright = "© Hayden Stites 2023"

[[module.imports]]
path = "github.com/willfaught/paige"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 20

[[languages.en.menu.main]]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 10

[[languages.en.menu.main]]
identifier = "programming"
name = "Programming"
url = "/programming/"
weight = 30

[[languages.en.menu.main]]
identifier = "art"
name = "3D Art"
url = "/art/"
weight = 40

[markup.goldmark.renderer]
unsafe = true
